// Generated by https://quicktype.io

export interface IPokemon {
  abilities: Ability[];
  base_experience: number;
  forms: NameAndUrl[];
  game_indices: GameIndex[];
  height: number;
  held_items: HeldItems[];
  id: number;
  is_default: boolean;
  location_area_encounters: string;
  moves: Move[];
  name: string;
  order: number;
  species: NameAndUrl;
  sprites: Sprites;
  stats: Stat[];
  types: Type[];
  weight: number;
}
export interface NameAndUrl {
  name: string;
  url: string;
}

export interface Ability {
  ability: NameAndUrl;
  is_hidden: boolean;
  slot: number;
}



export interface GameIndex {
  game_index: number;
  version: NameAndUrl;
}
export interface HeldItems {
  item: NameAndUrl;
  version_details: HeldItemsVersionDetails;
}
export interface HeldItemsVersionDetails {
  rarity: number;
  version: NameAndUrl;
}
export interface Move {
  move: NameAndUrl;
  version_group_details: VersionGroupDetail[];
}

export interface VersionGroupDetail {
  level_learned_at: number;
  move_learn_method: NameAndUrl;
  version_group: NameAndUrl;
}

export interface Sprites {
  back_default: string;
  back_female: null;
  back_shiny: string;
  back_shiny_female: null;
  front_default: string;
  front_female: null;
  front_shiny: string;
  front_shiny_female: null;
}

export interface Stat {
  base_stat: number;
  effort: number;
  stat: NameAndUrl;
}

export interface Type {
  slot: number;
  type: NameAndUrl;
}
